### ISSUE TITLE
Groups are deprecated in Protocol Buffers and unsupported by this library

### ISSUE THREAD

**Issue by manti-by** [drslump/Protobuf-PHP#10]
Hi.
I'm having such a mistake and I understand the message I have got, but I have no other way to get the data coming in this request. Maybe you have older versions of your library, which supports this data type or you can provide some code snippets, which will be helpful for me to resolve this problem.

**Comment by drslump** [comment]
"groups" are actually quite old and I haven't seen them used but a common reason for this error is because the message is malformed or you're trying to decode it with a wrong message definition. Make sure you're parsing the data with the correct message class.

If the message actually uses "groups", the only think I could recommend you is to either use the official Google library in Python for example or use the `protoc` command line tool to parse the data and process it manually from its textformart representation.

**Comment by nabeelio** [comment]
I'm running into this as well, but not using any groups in my proto files
Would there be in some case that it's throwing a false-positive? All of the messages seem to match up to the correct definitions (they get parsed to desc files by protoc without an issue)
