### ISSUE TITLE
_has() behaves incorrectly

### ISSUE THREAD

**Issue by cavedon** [drslump/Protobuf-PHP#8]
Hi,
it looks like that Message::_has() is not behaving according to the specifications. See the following example:

Given the following PB definition:
```package mytest;
message Test {
    optional bool mybool = 1 [default = false];
}

``````

and the following code:
```$test = new \mytest\Test();
$codec = new \DrSlump\Protobuf\Codec\TextFormat();
echo $codec->encode($test);
``````

The output is:
```mybool: true

```

While it should be empty because "mybool" was not set (or maybe the default value "false", but deninitely not "true").

I tracked this bug to the fact that Message::_has() return true if the descriptor has a field with that tag, but not whether the field has been set or not (as it should).

Do you confirm this?
Or am I misusing the library?
What is the easiest way to fix this?

Thanks!
Ludovico
```

**Comment by drslump** [comment]
Actually the bug is in the code generation step, if you look at the generated php file you'll see that the Test class is defined with a public property `$mybool` set to true. It's been fixed in the master branch.

Regarding the semantics of `_has`, it actually checks both, if the field is defined and if it does then checks if its value is different from `null`. Unfortunately the current design of the message classes does not take into account default values. This will be fixed shortly with a new released based on the `lazy` branch version of the library.

thanks!

**Comment by cavedon** [comment]
Thank you for the quick response and fix.
